import Head from "next/head";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Vechaiui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-blue-500">
          Welcome to <a href="#">Vechaiui.js!</a>
        </h1>
      </main>
    </div>
  );
}
